<?php
require_once __DIR__.'/../lib/db.php';
require_once __DIR__.'/../lib/auth.php';
require_login();

$article_id = $_GET['id'] ?? 0;

if (!$article_id) {
    http_response_code(400);
    exit('Invalid article ID');
}

$pdo = get_pdo();

// Get article with store info
$stmt = $pdo->prepare('
    SELECT a.*, s.name as store_name, s.admin_email as store_email
    FROM articles a
    JOIN stores s ON a.store_id = s.id
    WHERE a.id = ?
');
$stmt->execute([$article_id]);
$article = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$article) {
    http_response_code(404);
    exit('Article not found');
}

// Parse images
$images = [];
if (!empty($article['images'])) {
    $decoded = json_decode($article['images'], true);
    if (is_array($decoded)) {
        foreach ($decoded as $img) {
            $path = $img['local_path'] ?? '';
            if ($path) {
                // Build full URL for WordPress to download
                $protocol = isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http';
                $host = $_SERVER['HTTP_HOST'];
                $imageUrl = $protocol . '://' . $host . '/public/' . ltrim($path, '/');

                $images[] = [
                    'url' => $imageUrl,
                    'filename' => $img['filename'] ?? basename($path),
                    'path' => $path
                ];
            }
        }
    }
}

// Map status
$statusMap = [
    'approved' => 'publish',
    'submitted' => 'pending',
    'draft' => 'draft',
    'rejected' => 'draft'
];
$wpStatus = $statusMap[$article['status']] ?? 'draft';

// Format dates for WordPress
$postDate = date('Y-m-d H:i:s', strtotime($article['created_at']));
$postDateGmt = gmdate('Y-m-d H:i:s', strtotime($article['created_at']));

// Prepare content - ensure it's properly formatted
$content = $article['content'];

// Build category and tags
$categories = [];
$tags = [];

// Add category if available
if (!empty($article['category'])) {
    $categories[] = $article['category'];
}

// Parse tags if available
if (!empty($article['tags'])) {
    $tags = array_map('trim', explode(',', $article['tags']));
}

// Helper function to escape XML
function xml_escape($str) {
    return htmlspecialchars($str, ENT_XML1 | ENT_QUOTES, 'UTF-8');
}

// Start generating WXR
header('Content-Type: application/xml; charset=utf-8');
header('Content-Disposition: attachment; filename="article-' . $article_id . '-wordpress.xml"');

echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
?>
<!-- This is a WordPress eXtended RSS file generated by Cosmick Media Store Uploader -->
<!-- This file contains article data and can be imported into WordPress via Tools → Import → WordPress -->
<rss version="2.0"
    xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:wfw="http://wellformedweb.org/CommentAPI/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:wp="http://wordpress.org/export/1.2/">

<channel>
    <title><?php echo xml_escape($article['store_name']); ?> - Article Export</title>
    <link><?php echo xml_escape('http://' . $_SERVER['HTTP_HOST']); ?></link>
    <description>Article export from Cosmick Media Store Uploader</description>
    <pubDate><?php echo date('D, d M Y H:i:s +0000'); ?></pubDate>
    <language>en-US</language>
    <wp:wxr_version>1.2</wp:wxr_version>
    <wp:base_site_url><?php echo xml_escape('http://' . $_SERVER['HTTP_HOST']); ?></wp:base_site_url>
    <wp:base_blog_url><?php echo xml_escape('http://' . $_SERVER['HTTP_HOST']); ?></wp:base_blog_url>

    <!-- Author -->
    <wp:author>
        <wp:author_id>1</wp:author_id>
        <wp:author_login><?php echo xml_escape(strtolower(str_replace(' ', '_', $article['store_name']))); ?></wp:author_login>
        <wp:author_email><?php echo xml_escape($article['store_email'] ?: 'noreply@example.com'); ?></wp:author_email>
        <wp:author_display_name><![CDATA[<?php echo $article['store_name']; ?>]]></wp:author_display_name>
        <wp:author_first_name><![CDATA[<?php echo $article['store_name']; ?>]]></wp:author_first_name>
        <wp:author_last_name><![CDATA[]]></wp:author_last_name>
    </wp:author>

    <!-- Categories -->
<?php foreach ($categories as $cat): ?>
    <wp:category>
        <wp:term_id><?php echo crc32($cat); ?></wp:term_id>
        <wp:category_nicename><?php echo xml_escape(strtolower(str_replace(' ', '-', $cat))); ?></wp:category_nicename>
        <wp:category_parent></wp:category_parent>
        <wp:cat_name><![CDATA[<?php echo ucfirst($cat); ?>]]></wp:cat_name>
    </wp:category>
<?php endforeach; ?>

    <!-- Tags -->
<?php foreach ($tags as $tag): ?>
    <wp:tag>
        <wp:term_id><?php echo crc32($tag); ?></wp:term_id>
        <wp:tag_slug><?php echo xml_escape(strtolower(str_replace(' ', '-', $tag))); ?></wp:tag_slug>
        <wp:tag_name><![CDATA[<?php echo $tag; ?>]]></wp:tag_name>
    </wp:tag>
<?php endforeach; ?>

<?php
// Generate attachment items for images
$attachmentId = 1000;
foreach ($images as $idx => $image):
    $attachmentId++;
?>
    <!-- Image Attachment <?php echo $idx + 1; ?> -->
    <item>
        <title><?php echo xml_escape($image['filename']); ?></title>
        <link><?php echo xml_escape($image['url']); ?></link>
        <pubDate><?php echo date('D, d M Y H:i:s +0000', strtotime($article['created_at'])); ?></pubDate>
        <dc:creator><![CDATA[<?php echo $article['store_name']; ?>]]></dc:creator>
        <guid isPermaLink="false"><?php echo xml_escape($image['url']); ?></guid>
        <description></description>
        <content:encoded><![CDATA[]]></content:encoded>
        <excerpt:encoded><![CDATA[]]></excerpt:encoded>
        <wp:post_id><?php echo $attachmentId; ?></wp:post_id>
        <wp:post_date><?php echo $postDate; ?></wp:post_date>
        <wp:post_date_gmt><?php echo $postDateGmt; ?></wp:post_date_gmt>
        <wp:comment_status>closed</wp:comment_status>
        <wp:ping_status>closed</wp:ping_status>
        <wp:post_name><?php echo xml_escape(pathinfo($image['filename'], PATHINFO_FILENAME)); ?></wp:post_name>
        <wp:status>inherit</wp:status>
        <wp:post_parent>0</wp:post_parent>
        <wp:menu_order>0</wp:menu_order>
        <wp:post_type>attachment</wp:post_type>
        <wp:post_password></wp:post_password>
        <wp:is_sticky>0</wp:is_sticky>
        <wp:attachment_url><?php echo xml_escape($image['url']); ?></wp:attachment_url>
        <wp:postmeta>
            <wp:meta_key>_wp_attached_file</wp:meta_key>
            <wp:meta_value><![CDATA[<?php echo $image['filename']; ?>]]></wp:meta_value>
        </wp:postmeta>
    </item>
<?php endforeach; ?>

    <!-- Main Article Post -->
    <item>
        <title><?php echo xml_escape($article['title']); ?></title>
        <link></link>
        <pubDate><?php echo date('D, d M Y H:i:s +0000', strtotime($article['created_at'])); ?></pubDate>
        <dc:creator><![CDATA[<?php echo $article['store_name']; ?>]]></dc:creator>
        <guid isPermaLink="false"></guid>
        <description></description>
        <content:encoded><![CDATA[<?php echo $content; ?>]]></content:encoded>
        <excerpt:encoded><![CDATA[<?php echo $article['excerpt'] ?: strip_tags(substr($content, 0, 200)); ?>]]></excerpt:encoded>
        <wp:post_id><?php echo $article_id; ?></wp:post_id>
        <wp:post_date><?php echo $postDate; ?></wp:post_date>
        <wp:post_date_gmt><?php echo $postDateGmt; ?></wp:post_date_gmt>
        <wp:comment_status>open</wp:comment_status>
        <wp:ping_status>open</wp:ping_status>
        <wp:post_name><?php echo xml_escape(strtolower(str_replace(' ', '-', $article['title']))); ?></wp:post_name>
        <wp:status><?php echo $wpStatus; ?></wp:status>
        <wp:post_parent>0</wp:post_parent>
        <wp:menu_order>0</wp:menu_order>
        <wp:post_type>post</wp:post_type>
        <wp:post_password></wp:post_password>
        <wp:is_sticky>0</wp:is_sticky>

<?php foreach ($categories as $cat): ?>
        <category domain="category" nicename="<?php echo xml_escape(strtolower(str_replace(' ', '-', $cat))); ?>"><![CDATA[<?php echo ucfirst($cat); ?>]]></category>
<?php endforeach; ?>

<?php foreach ($tags as $tag): ?>
        <category domain="post_tag" nicename="<?php echo xml_escape(strtolower(str_replace(' ', '-', $tag))); ?>"><![CDATA[<?php echo $tag; ?>]]></category>
<?php endforeach; ?>

        <!-- Custom Fields -->
        <wp:postmeta>
            <wp:meta_key>_source_store</wp:meta_key>
            <wp:meta_value><![CDATA[<?php echo $article['store_name']; ?>]]></wp:meta_value>
        </wp:postmeta>
        <wp:postmeta>
            <wp:meta_key>_source_store_id</wp:meta_key>
            <wp:meta_value><![CDATA[<?php echo $article['store_id']; ?>]]></wp:meta_value>
        </wp:postmeta>
        <wp:postmeta>
            <wp:meta_key>_original_status</wp:meta_key>
            <wp:meta_value><![CDATA[<?php echo $article['status']; ?>]]></wp:meta_value>
        </wp:postmeta>
<?php if (!empty($article['admin_notes'])): ?>
        <wp:postmeta>
            <wp:meta_key>_admin_notes</wp:meta_key>
            <wp:meta_value><![CDATA[<?php echo $article['admin_notes']; ?>]]></wp:meta_value>
        </wp:postmeta>
<?php endif; ?>
<?php if (!empty($article['ip'])): ?>
        <wp:postmeta>
            <wp:meta_key>_submission_ip</wp:meta_key>
            <wp:meta_value><![CDATA[<?php echo $article['ip']; ?>]]></wp:meta_value>
        </wp:postmeta>
<?php endif; ?>

    </item>

</channel>
</rss>
